### ISSUE TITLE
*_HttpDependencyCorrelationInPostRequest flaky test

### ISSUE THREAD

**Issue by lmolkova** [microsoft/ApplicationInsights-dotnet-server#1096]
https://dev.azure.com/mseng/AppInsights/_build/results?buildId=7634250&view=ms.vss-test-web.test-result-details

**Comment by lmolkova** [comment]
[logs_7898263.zip](https://github.com/Microsoft/ApplicationInsights-dotnet-server/files/2641865/logs_7898263.zip)
+1

 2018-12-04T00:43:58.0088004Z Error Message:
2018-12-04T00:43:58.0088431Z  Assert.AreEqual failed. Expected:<2>. Actual:<1>. 
2018-12-04T00:43:58.0088596Z Stack Trace:
2018-12-04T00:43:58.0088906Z    at E2ETests.Test452Base.<TestHttpDependencyCorrelationInPostRequest>d__19.MoveNext() in E:\A\_work\250\s\Test\E2ETests\E2ETests\Test452Base.cs:line 328
2018-12-04T00:43:58.0089015Z --- End of stack trace from previous location where exception was thrown ---
2018-12-04T00:43:58.0089745Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2018-12-04T00:43:58.0090241Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-12-04T00:43:58.0090685Z    at E2ETests.Net462.Test452OnNet462.<Test452OnNet462_HttpDependencyCorrelationInPostRequest>d__14.MoveNext() in E:\A\_work\250\s\Test\E2ETests\E2ETests\net462\Test452OnNet462.cs:line 87
2018-12-04T00:43:58.0091022Z --- End of stack trace from previous location where exception was thrown ---
2018-12-04T00:43:58.0091178Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2018-12-04T00:43:58.0091266Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-12-04T00:43:58.0091741Z    at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.ThreadOperations.ExecuteWithAbortSafety(Action action)
2018-12-04T00:43:58.0091868Z 
2018-12-04T00:43:58.0105499Z Standard Output Messages:
2018-12-04T00:43:58.0105723Z

**Comment by lmolkova** [comment]
```
Failed   Test452OnNet462_HttpDependencyCorrelationInPostRequest
Error Message:
 Assert.AreEqual failed. Expected:<1>. Actual:<0>. 
Stack Trace:
   at E2ETests.Test452Base.<TestHttpDependencyCorrelationInPostRequest>d__19.MoveNext() in E:\A\_work\719\s\Test\E2ETests\E2ETests\Test452Base.cs:line 304
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at E2ETests.Net462.Test452OnNet462.<Test452OnNet462_HttpDependencyCorrelationInPostRequest>d__14.MoveNext() in E:\A\_work\719\s\Test\E2ETests\E2ETests\net462\Test452OnNet462.cs:line 87
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.ThreadOperations.ExecuteWithAbortSafety(Action action)

Standard Output Messages:
 

Debug Trace:
Started Test Initialize:3:10:20 AM
 Deleting items started:3:10:20 AM
 Deleting items for ikey:0786419e-d901-4373-902a-136921b63fb2
 vstest.console.exe Information: 0 : 3:10:20 AM Invoking url:http://172.28.134.171/api/Data/DeleteItems/?p=0786419e-d901-4373-902a-136921b63fb2
 vstest.console.exe Information: 0 : Received list of data items/errors from the data endpoint, data:["RemoteDependency\",\"time\":\"2019-05-22T03:10:19.8516854Z\",\"iKey\":\"0786419e-d901-4373-902a-136921b63fb2\",\"tags\":{\"ai.cloud.role","Request\",\"time\":\"2019-05-22T03:10:19.8479545Z\",\"iKey\":\"0786419e-d901-4373-902a-136921b63fb2\",\"tags\":{\"ai.cloud.roleInstance\"","Request\",\"time\":\"2019-05-22T03:10:19.8480217Z\",\"iKey\":\"0786419e-d901-4373-902a-136921b63fb2\",\"tags\":{\"ai.cloud.roleInstance\"","Message\",\"time\":\"2019-05-22T03:10:20.1430028Z\",\"iKey\":\"0786419e-d901-4373-902a-136921b63fb2\",\"tags\":{\"ai.cloud.roleInstance\""]
 Deleting items for ikey:dummy
 vstest.console.exe Information: 0 : 3:10:20 AM Invoking url:http://172.28.134.171/api/Data/DeleteItems/?p=dummy
 vstest.console.exe Information: 0 : Received list of data items/errors from the data endpoint, data:[]
 Deleting items for ikey:e45209bb-49ab-41a0-8065-793acb3acc56
 vstest.console.exe Information: 0 : 3:10:20 AM Invoking url:http://172.28.134.171/api/Data/DeleteItems/?p=e45209bb-49ab-41a0-8065-793acb3acc56
 vstest.console.exe Information: 0 : Received list of data items/errors from the data endpoint, data:["Request\",\"time\":\"2019-05-22T03:10:19.8455528Z\",\"iKey\":\"e45209bb-49ab-41a0-8065-793acb3acc56\",\"tags\":{\"ai.cloud.roleInstance\"","RemoteDependency\",\"time\":\"2019-05-22T03:10:19.8482128Z\",\"iKey\":\"e45209bb-49ab-41a0-8065-793acb3acc56\",\"tags\":{\"ai.cloud.role","Request\",\"time\":\"2019-05-22T03:10:19.8469393Z\",\"iKey\":\"e45209bb-49ab-41a0-8065-793acb3acc56\",\"tags\":{\"ai.cloud.roleInstance\"","Request\",\"time\":\"2019-05-22T03:10:20.8755447Z\",\"iKey\":\"e45209bb-49ab-41a0-8065-793acb3acc56\",\"tags\":{\"ai.cloud.roleInstance\"","Request\",\"time\":\"2019-05-22T03:10:20.8769449Z\",\"iKey\":\"e45209bb-49ab-41a0-8065-793acb3acc56\",\"tags\":{\"ai.cloud.roleInstance\""]
 Deleting items completed:3:10:20 AM
 Docker PS Stats at After MyTestInitialize3:10:20 AM
 Executing cmd command: /c docker ps -a
 Output from cmd command:CONTAINER ID        IMAGE                                    COMMAND                   CREATED             STATUS              PORTS               NAMES
09832af761d7        e2etests_e2etestwebapp                   "C:\\ServiceMonitor..."   2 minutes ago       Up 2 minutes        80/tcp              e2etests_e2etestwebapp_1
d0b0e9d653c8        e2etests_e2etestwebappcore20             "dotnet E2ETestApp..."    2 minutes ago       Up 2 minutes        80/tcp              e2etests_e2etestwebappcore20_1
9754bb3e009c        e2etests_e2etestwebapi                   "C:\\ServiceMonitor..."   2 minutes ago       Up 2 minutes        80/tcp              e2etests_e2etestwebapi_1
ad95507507fe        e2etests_azureemulator                   "cmd /S /C C:\\entr..."   2 minutes ago       Up 2 minutes        10000-10002/tcp     e2etests_azureemulator_1
85ab2ed9830a        e2etests_ingestionservice                "C:\\ServiceMonitor..."   2 minutes ago       Up 2 minutes        80/tcp              e2etests_ingestionservice_1
5d891b0f179b        microsoft/mssql-server-windows-express   "powershell -Comma..."    2 minutes ago       Up 2 minutes                            e2etests_sql-server_1

 Completed Test Initialize:3:10:21 AM
 Response Headers: 
 	Pragma = no-cache
 	OnExecuteRequestStep = True
 	.NetRelease = 394802
 	AspNetAssemblyVersion = 4.7.2623.0
 	RestoredActivityId = |e7ca6bfd-6f71-4144-9869-8d6fda949022.bfdbdd33_bfdbdd34_
 	BodyLength = 1048576
 	Cache-Control = no-cache
 	Date = Wed, 22 May 2019 03:10:20 GMT
 	Server = Microsoft-IIS/10.0
 	X-AspNet-Version = 4.0.30319
 	X-Powered-By = ASP.NET
 vstest.console.exe Information: 0 : 3:10:22 AM Invoking url:http://172.28.134.171/api/Data/GetItem/?p=0786419e-d901-4373-902a-136921b63fb2
 Hitting the target url:http://172.28.134.119/Dependencies?type=flush
 Exception occured:System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at E2ETests.Test452Base.<ExecuteWebRequestToTarget>d__79.MoveNext() in E:\A\_work\719\s\Test\E2ETests\E2ETests\Test452Base.cs:line 1219
 vstest.console.exe Information: 0 : 3:10:23 AM Invoking url:http://172.28.134.171/api/Data/GetItem/?p=0786419e-d901-4373-902a-136921b63fb2
 Hitting the target url:http://172.28.134.119/Dependencies?type=flush
 Exception occured:System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at E2ETests.Test452Base.<ExecuteWebRequestToTarget>d__79.MoveNext() in E:\A\_work\719\s\Test\E2ETests\E2ETests\Test452Base.cs:line 1219
 vstest.console.exe Information: 0 : 3:10:24 AM Invoking url:http://172.28.134.171/api/Data/GetItem/?p=0786419e-d901-4373-902a-136921b63fb2
 Hitting the target url:http://172.28.134.119/Dependencies?type=flush
 Exception occured:System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at E2ETests.Test452Base.<ExecuteWebRequestToTarget>d__79.MoveNext() in E:\A\_work\719\s\Test\E2ETests\E2ETests\Test452Base.cs:line 1219
 vstest.console.exe Information: 0 : 3:10:25 AM Invoking url:http://172.28.134.171/api/Data/GetItem/?p=0786419e-d901-4373-902a-136921b63fb2
 Hitting the target url:http://172.28.134.119/Dependencies?type=flush
 Exception occured:System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at E2ETests.Test452Base.<ExecuteWebRequestToTarget>d__79.MoveNext() in E:\A\_work\719\s\Test\E2ETests\E2ETests\Test452Base.cs:line 1219
 vstest.console.exe Information: 0 : 3:10:26 AM Invoking url:http://172.28.134.171/api/Data/GetItem/?p=0786419e-d901-4373-902a-136921b63fb2
 Hitting the target url:http://172.28.134.119/Dependencies?type=flush
 Exception occured:System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at E2ETests.Test452Base.<ExecuteWebRequestToTarget>d__79.MoveNext() in E:\A\_work\719\s\Test\E2ETests\E2ETests\Test452Base.cs:line 1219
 Items received in iteration: 5
 Dependencies count for WebApp:0
 Started Test Cleanup:3:10:26 AM
 Docker PS Stats at After MyTestCleanup3:10:26 AM
 Executing cmd command: /c docker ps -a
 Output from cmd command:CONTAINER ID        IMAGE                                    COMMAND                   CREATED             STATUS              PORTS               NAMES
09832af761d7        e2etests_e2etestwebapp                   "C:\\ServiceMonitor..."   2 minutes ago       Up 2 minutes        80/tcp              e2etests_e2etestwebapp_1
d0b0e9d653c8        e2etests_e2etestwebappcore20             "dotnet E2ETestApp..."    2 minutes ago       Up 2 minutes        80/tcp              e2etests_e2etestwebappcore20_1
9754bb3e009c        e2etests_e2etestwebapi                   "C:\\ServiceMonitor..."   2 minutes ago       Up 2 minutes        80/tcp              e2etests_e2etestwebapi_1
85ab2ed9830a        e2etests_ingestionservice                "C:\\ServiceMonitor..."   2 minutes ago       Up 2 minutes        80/tcp              e2etests_ingestionservice_1
ad95507507fe        e2etests_azureemulator                   "cmd /S /C C:\\entr..."   2 minutes ago       Up 2 minutes        10000-10002/tcp     e2etests_azureemulator_1
5d891b0f179b        microsoft/mssql-server-windows-express   "powershell -Comma..."    2 minutes ago       Up 2 minutes                            e2etests_sql-server_1

 Completed Test Cleanup:3:10:26 AM
```
