### ISSUE TITLE
Flaky  test PerformanceCollectorNormalizedCpuCounterTest

### ISSUE THREAD

**Issue by lmolkova** [Microsoft/ApplicationInsights-dotnet-server#1125]
https://dev.azure.com/mseng/AppInsights/_build/results?buildId=7895457

**Comment by lmolkova** [comment]
https://dev.azure.com/mseng/AppInsights/_build/results?buildId=7898264

**Comment by lmolkova** [comment]
```
2018-12-31T20:53:04.0554843Z Failed   PerformanceCollectorNormalizedCpuCounterTest
2018-12-31T20:53:04.0555120Z Error Message:
2018-12-31T20:53:04.0555584Z  Assert.IsTrue failed. 
2018-12-31T20:53:04.0555892Z Stack Trace:
2018-12-31T20:53:04.0556204Z    at Microsoft.ApplicationInsights.Tests.PerformanceCollectorTestBase.PerformanceCollectorNormalizedCpuTest(IPerformanceCollector collector) in D:\a\1\s\Src\PerformanceCollector\Perf.NetFull.Tests\PerformanceCollectorTestBase.cs:line 208
2018-12-31T20:53:04.0556590Z    at Microsoft.ApplicationInsights.Tests.StandardPerformanceCollectorTests.PerformanceCollectorNormalizedCpuCounterTest() in D:\a\1\s\Src\PerformanceCollector\Perf.NetFull.Tests\StandardPerformanceCollectorTests.cs:line 51
2018-12-31T20:53:04.0556850Z 
```
https://dev.azure.com/mseng/AppInsights/_build/results?buildId=8102966&_a=summary
