### ISSUE TITLE
HttpCoreDiagnosticListener tracks exceptions 

### ISSUE THREAD

**Issue by lmolkova** [microsoft/ApplicationInsights-dotnet-server#1225]
When HttpClient call fails with an exception (like network issue), DiagnosticSource sends Exception events.
This event should be ignored: likely exception is handled, corresponding HTTP request is logged with error and it just creates noise.

Unhandled exceptions are tracked through ASP.NET Core, GenericHost, WebJib extensions, loggers, etc....

**Comment by gonzalolorieto** [comment]
Can you provide some example over what exceptions are thrown?

Also, we current have posted an issue on Azure Support that seems related.

> CONCURRENTAPPEND failed with   Unknown Error: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond Source: System.Net.Requests StackTrace:    at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
>    at System.Net.WebRequest.<>c.<GetResponseAsync>b__68_2(IAsyncResult iar)
>    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.Azure.DataLake.Store.WebTransport.MakeSingleCallAsync(String opCode, String path, ByteBuffer requestData, ByteBuffer responseData, QueryParams qp, AdlsClient client, RequestOptions req, OperationResponse resp, CancellationToken cancelToken, IDictionary`2 customHeaders).
> 
> Exception type
> Microsoft.Azure.DataLake.Store.AdlsException	

Could this be related? 

Regards

**Comment by cijothomas** [comment]
This issue is about DependencyCollection module tracking an Exception event along with a DependencyTelemetry in the event of client side errors like DNS. The exception is sent to user ikey, along with DependencyTelemetry.

If this exception is not tracked, then the only information DependencyCollector has is that call failed, and resultCode as "Faulted". We should modify the result code to be more useful, before removing the actual exception.

Btw, DependencyCollection for .NET Framework does not track this exception, so making netcore also behave same is good for consistency point.
