### ISSUE TITLE
Functional dependency tests failure. Message: System.NullReferenceException

### ISSUE THREAD

**Issue by abaranch** [Microsoft/ApplicationInsights-dotnet-server#163]
4.6 framework + StatusMonitor + remote dependency tests

vstest.executionengine.x86.exe Information: 0 : 12:55:21. Application Trace. Level: Warning; Id: 54; Message: TransmissionSendingFailed. TransmissionId: MWIwvbx1Jdg=. Message: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl(Func`3 beginMethod, Func`2 endFunction, Action`1 endAction, Object state, TaskCreationOptions creationOptions)
   at System.Net.WebRequest.<GetRequestStreamAsync>b__77_1()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ApplicationInsights.Channel.Transmission.<SendRequestAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ApplicationInsights.Channel.Transmission.<SendAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.Implementation.TransmissionSender.<StartSending>d__10.MoveNext().; 
    DateTime=2016-09-30T19:55:22.6756151Z
vstest.executionengine.x86.exe Information: 0 : 12:55:21. Application Trace. Level: Warning; Id: 54; Message: TransmissionSendingFailed. TransmissionId: MWIwvbx1Jdg=. Message: Object reference not set to an instance of an object..;

**Comment by abaranch** [comment]
Fails here: https://github.com/Microsoft/ApplicationInsights-dotnet/blob/37cec526194b833f7cd676f25eafd985dd88d3fa/src/Core/Managed/Shared/Channel/Transmission.cs#L226

**Comment by SergeyKanzhelev** [comment]
I enabled the new event source for traces in functional tests: `"Microsoft-ApplicationInsights-Extensibility-Rtia-SharedCore"`. It gave me the error:

```
vstest.executionengine.x86.exe Information: 0 : 02:35:33. Application Trace. Level: Warning; Id: 1; Message: End callback failed with exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Diagnostics.Instrumentation.Extensions.Intercept.Functions.<>c__DisplayClass3_0.<Decorate>b__1(Object a, Object b, Object arg0, Object arg1, Object arg2).;
```

So it is an Intercept error
C:\src\mseng\APMC-v2\src\prod\core\ProfilerCallbacks\FunctionsAuto.cs

Need to replace `return null` to `return b`:
```
try
{
return endCallback(a, b, arg0, arg1, arg2, arg3, arg4, arg5);
}
catch (Exception exp)
{
RtiaSharedCoreEventSource.Log.CallbackFailedWithException("End", exp.ToString());
}
return null; -> return b
```

**Comment by abaranch** [comment]
@SergeyKanzhelev Did not help

**Comment by abaranch** [comment]
Sorry, looked into a wrong build. This fixed the issue.
