### ISSUE TITLE
No request telemetry in AddTargetHashForResponseHeader

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-dotnet-server#569]
There are two situations when this method will throw NullReferenceException - when `TelemetryCorrelationHttpModule` defined after the `ApplicationInsightsHttpModule` and when End callback happens before the `AddOnSendingHeaders` event.

Need to handle this situation better. Consider not cleaning the `HttpContext.Items`

``` csharp
        public void AddTargetHashForResponseHeader(HttpContext context)
        {
            if (this.telemetryClient == null)
            {
                throw new InvalidOperationException();
            }

            var requestTelemetry = context.GetRequestTelemetry();

            if (string.IsNullOrEmpty(requestTelemetry.Context.InstrumentationKey))
```

**Comment by SergeyKanzhelev** [comment]
CC: @lmolkova FYI

**Comment by lmolkova** [comment]
We never clean up requestTelemetry from the context. Probably requestTelemetry was never created (because the TelemetryCorrelationHttpModule has not yet(?) sent event).

Do you have more info? Reproduce it?

**Comment by SergeyKanzhelev** [comment]
I didn't have `AspNetDiagnosticTelemetryModule` telemetry module added to the `ApplicationInsights.config`. Now 4 pieces needs to be configured =) Quite fragile, need to make it more reliable in 2.5

**Comment by SergeyKanzhelev** [comment]
When upgrading to the latest SDK (2.4) you need to make sure the following changes applied to `web.config` and `ApplicationInsights.config`:

1. Two http modules instead of one. In `web.config` you should have two http modules. Order is important for some scenarios:

    ``` xml
    <system.webServer>
      <modules>
          <add name="TelemetryCorrelationHttpModule" type="Microsoft.AspNet.TelemetryCorrelation.TelemetryCorrelationHttpModule, Microsoft.AspNet.TelemetryCorrelation" preCondition="integratedMode,managedHandler" />
          <add name="ApplicationInsightsHttpModule" type="Microsoft.ApplicationInsights.Web.ApplicationInsightsHttpModule, Microsoft.AI.Web" preCondition="managedHandler" />
      </modules>
    </system.webServer>
    ```

2. In `ApplicationInsights.config` in addition to `RequestTrackingTelemetryModule` you should have the following telemetry module:

    ``` xml
    <TelemetryModules>
      <Add Type="Microsoft.ApplicationInsights.Web.AspNetDiagnosticTelemetryModule, Microsoft.AI.Web"/>
    </TelemetryModules>
    ```

**Comment by Dmitry-Matveev** [comment]
@SergeyKanzhelev , is this something we can see in the telemetry to figure out how widespread the impact is? If not - did you have a better design in mind to take into 2.5?

**Comment by SergeyKanzhelev** [comment]
@Dmitry-Matveev perfect timing for the question. See https://github.com/aspnet/Microsoft.AspNet.TelemetryCorrelation/issues/21 for example =).

I heard many complains and experienced it myself. It's just hard to troubleshoot and error prone.

**Comment by Daniel-Svensson** [comment]
We also had this problem after installing 2.4.

We use project.json and maybe that makes it work less ideal.

Could you update the release notes (on github) with a hint that this is a known issue?

**Comment by SergeyKanzhelev** [comment]
Example report from one customer:

```
AI (Internal): TelemetryInitializer Microsoft.ApplicationInsights.Web.OperationCorrelationTelemetryInitializer failed to initialize telemetry item System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AspNet.TelemetryCorrelation, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.AspNet.TelemetryCorrelation, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at Microsoft.ApplicationInsights.Web.Implementation.RequestTrackingExtensions.CreateRequestTelemetryPrivate(HttpContext platformContext)
   at Microsoft.ApplicationInsights.Web.Implementation.RequestTrackingExtensions.ReadOrCreateRequestTelemetryPrivate(HttpContext platformContext)
   at Microsoft.ApplicationInsights.Web.Implementation.WebTelemetryInitializerBase.Initialize(ITelemetry telemetry)
```

See https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues/671

**Comment by AC740** [comment]
modules already have ApplicationInsightsWebTracking 
<add name="ApplicationInsightsWebTracking" type="Microsoft.ApplicationInsights.Web.ApplicationInsightsHttpModule, Microsoft.AI.Web" preCondition="managedHandler" />

Do I need to add this as well after that?
<add name="ApplicationInsightsHttpModule" type="Microsoft.ApplicationInsights.Web.ApplicationInsightsHttpModule, Microsoft.AI.Web" preCondition="managedHandler" />

**Comment by Dmitry-Matveev** [comment]
@AC740, name is the only difference between the two modules you mentioned, so you won't need to register the same module with the different name again. You'd need to make sure that you have both types registered, `Microsoft.AspNet.TelemetryCorrelation.TelemetryCorrelationHttpModule` and `Microsoft.ApplicationInsights.Web.ApplicationInsightsHttpModule`:

      <add name="TelemetryCorrelationHttpModule" type="Microsoft.AspNet.TelemetryCorrelation.TelemetryCorrelationHttpModule, Microsoft.AspNet.TelemetryCorrelation" preCondition="integratedMode,managedHandler" />
      <add name="ApplicationInsightsHttpModule" type="Microsoft.ApplicationInsights.Web.ApplicationInsightsHttpModule, Microsoft.AI.Web" preCondition="managedHandler" />

**Comment by greigs** [comment]
For anyone who finds this with intermittent issues with performance telemetry not being collected after a redeploy / reset of the application. I fixed the issue I was having by adding the following in additional to the config described here...

```
<system.webServer>
    <modules>
      <remove name="TelemetryCorrelationHttpModule" />
      <add name="TelemetryCorrelationHttpModule" type="Microsoft.AspNet.TelemetryCorrelation.TelemetryCorrelationHttpModule, Microsoft.AspNet.TelemetryCorrelation" preCondition="managedHandler" />
      <remove name="ApplicationInsightsWebTracking" />
      <add name="ApplicationInsightsWebTracking" type="Microsoft.ApplicationInsights.Web.ApplicationInsightsHttpModule, Microsoft.AI.Web" preCondition="managedHandler" />
    </modules>

```
