### ISSUE TITLE
System.InvalidOperationException: Can't start collection while it is already running.

### ISSUE THREAD

**Issue by jfloodnet** [Microsoft/ApplicationInsights-dotnet-server#794]
I have an Service Fabric application with 3 services. 1. Stateful Actor Service, 1 Stateless Service and 1 Stateless Aspnetcore Service targeting .Net Framework 4.6.1

All three services have identical applicationinsights.config 
[ApplicationInsights.config.txt](https://github.com/Microsoft/ApplicationInsights-dotnet-server/files/1640859/ApplicationInsights.config.txt)

When going to the Live Metrics i see the following error repeatedly in the telemetry log. This error has only begun after adding the Stateless Aspnetcore Serivce in the mix. Any tips on how I can troubleshoot this would be appreciated. cheers

AI (Internal): Unexpected error in QuickPulse infrastructure: System.InvalidOperationException: Can't start collection while it is already running.
   at Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.QuickPulse.QuickPulseTelemetryProcessor.Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.QuickPulse.IQuickPulseTelemetryProcessor.StartCollection(IQuickPulseDataAccumulatorManager accumulatorManager, Uri serviceEndpoint, TelemetryConfiguration configuration, Boolean disableFullTelemetryItems)
   at Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.QuickPulse.QuickPulseTelemetryModule.OnStartCollection()
   at Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.Implementation.QuickPulse.QuickPulseCollectionStateManager.UpdateState(String instrumentationKey, String authApiKey)
   at Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.QuickPulse.QuickPulseTelemetryModule.StateThreadWorker(Object state). QuickPulse data will not be available.

**Comment by jfloodnet** [comment]
Hi @MS-TimothyMothra - sorry for the late response.
I've installed Microsoft.ApplicationInsights.AspNetCore v2.1.1

cheers,

**Comment by Dmitry-Matveev** [comment]
@tokaplan, is this something you know about, maybe a duplicate?

**Comment by jfloodnet** [comment]
So was this issue a duplicate?

**Comment by Dmitry-Matveev** [comment]
If some of the services are within the same appdomain, I'd expect that the first quick pulse module is loaded and operational after the first service initialization but the second one fails [on this check](https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/4093e9a6d350a9d4759eb64a2be17a90dc23f85a/Src/PerformanceCollector/Perf.Shared/QuickPulseTelemetryProcessor.cs#L117).
With that, excluding the quick pulse module from the second service config might help.

Good t-shooting steps are described [here](http://sergeysharp.com/blog/2015/04/16/diagnostic-of-applicationinsights-sdk/) and [here](http://www.apmtips.com/blog/2015/11/07/application-insights-self-diagnostic/).

@tokaplan would know more on this.
