### ISSUE TITLE
Flaky test: OnEndExceptionAsyncDoesNotSendTelemetryIfSuccess_1ArgumentOverride

### ISSUE THREAD

**Issue by lmolkova** [microsoft/ApplicationInsights-dotnet-server#974]
```
Assert.IsTrue failed. Incorrect duration. Collected 2.9989 should be less than max 1.4196
Stack trace
   at Microsoft.ApplicationInsights.Tests.ProfilerSqlProcessingTest.ValidateTelemetryPacket(DependencyTelemetry remoteDependencyTelemetryActual, String expectedName, Boolean expectedSuccess, String expectedResultCode, Double timeBetweenBeginEndInMs, Boolean async) in E:\A\_work\110\s\Src\DependencyCollector\Shared.Tests\Implementation\ProfilerSqlProcessingTest.cs:line 716
   at Microsoft.ApplicationInsights.Tests.ProfilerSqlProcessingTest.OnEndExceptionAsyncDoesNotSendTelemetryIfSuccess_1ArgumentOverride() in E:\A\_work\110\s\Src\DependencyCollector\Shared.Tests\Implementation\ProfilerSqlProcessingTest.cs:line 578
```

https://mseng.visualstudio.com/AppInsights/AppInsights%20Team/_build/results?buildId=6926408&view=ms.vss-test-web.test-result-details

**Comment by lmolkova** [comment]
fixed with #1200
